# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.21

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /home/keti/KETI_BMC/KETI-APP/sysroots/x86_64-oesdk-linux/usr/bin/cmake

# The command to remove a file.
RM = /home/keti/KETI_BMC/KETI-APP/sysroots/x86_64-oesdk-linux/usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/keti/KETI_BMC/KETI-APP/hj/app/IBMC-APP/test/Policy

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/keti/KETI_BMC/KETI-APP/hj/app/IBMC-APP/test/Policy

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/home/keti/KETI_BMC/KETI-APP/sysroots/x86_64-oesdk-linux/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/home/keti/KETI_BMC/KETI-APP/sysroots/x86_64-oesdk-linux/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/keti/KETI_BMC/KETI-APP/hj/app/IBMC-APP/test/Policy/CMakeFiles /home/keti/KETI_BMC/KETI-APP/hj/app/IBMC-APP/test/Policy//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/keti/KETI_BMC/KETI-APP/hj/app/IBMC-APP/test/Policy/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named KETI-Policy

# Build rule for target.
KETI-Policy: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 KETI-Policy
.PHONY : KETI-Policy

# fast build rule for target.
KETI-Policy/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KETI-Policy.dir/build.make CMakeFiles/KETI-Policy.dir/build
.PHONY : KETI-Policy/fast

policy.o: policy.cpp.o
.PHONY : policy.o

# target to build an object file
policy.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KETI-Policy.dir/build.make CMakeFiles/KETI-Policy.dir/policy.cpp.o
.PHONY : policy.cpp.o

policy.i: policy.cpp.i
.PHONY : policy.i

# target to preprocess a source file
policy.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KETI-Policy.dir/build.make CMakeFiles/KETI-Policy.dir/policy.cpp.i
.PHONY : policy.cpp.i

policy.s: policy.cpp.s
.PHONY : policy.s

# target to generate assembly for a file
policy.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/KETI-Policy.dir/build.make CMakeFiles/KETI-Policy.dir/policy.cpp.s
.PHONY : policy.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... KETI-Policy"
	@echo "... policy.o"
	@echo "... policy.i"
	@echo "... policy.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

